<a href="https://colab.research.google.com/github/emmataguinod/Linear-Algebra_2ndSem/blob/main/Copy_of_Laboratory_3_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 3 : Matrix Operations

## Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)


In [ ]:
AT2 = A.T

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [ ]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [ ]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
A = np.array([
    [13,12,11],
    [4,15,1],
    [1,11,10]
])
B = np.array([
    [24,21,36],
    [14,21,19],
    [31,24,38]
])
C = np.array([
    [13,12,30],
    [30,21,11],
    [11,10,21]
])

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [11,42],
    [20,33]
])
np.linalg.det(A)

-476.9999999999997

In [ ]:
B = np.array([
    [10,22,-2],
    [24,43,-3],
    [14,53,4]
])
np.linalg.det(B)

-1065.9999999999998

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [11,17],
    [-8, 25]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
    [7,8,9],
    [4,6,-3],
    [6,8,12]
])
Q = np.linalg.inv(P)
Q

array([[ 0.88888889, -0.22222222, -0.72222222],
       [-0.61111111,  0.27777778,  0.52777778],
       [-0.03703704, -0.07407407,  0.09259259]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -1.11022302e-16,  2.49800181e-16],
       [-5.55111512e-17,  1.00000000e+00,  1.38777878e-16],
       [ 2.22044605e-16,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

##Task 1

In [3]:
A = np.array([
    [2,4,6],
    [5,7,8],  
    [4,2,9]  
])

B = np.array([
   [7,4,9],
   [15,6,8],  
   [14,22,5]            
])

C = np.array([
    [5,6,8],
    [12,4,7], 
    [8,9,8]
])

In [4]:
# Commutative Property (First Property)
print("The First Property states A*B is Not Equal to B*A")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()

x = A@B
print("A@B\n\n{}".format(x))
print()
y = B@A
print("B@A\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is A@B equal to B@A? \n")
print(a)

The First Property states A*B is Not Equal to B*A

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

A@B

[[158 164  80]
 [252 238 141]
 [184 226  97]]

B@A

[[ 70  74 155]
 [ 92 118 210]
 [158 220 305]]

Is A@B equal to B@A? 

False


In [5]:
# Associative Property (Second Property)
print("The Second Property states A@(B@C) = (A@B)@C")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()
print("Matrix C: \n{}".format(C))
print()

x = A@(B@C)
print("A@(B@C)\n\n{}".format(x))
print()
y = (A@B)@C
print("(A@B)@C\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is the Associative Property True? \n")
print(a)

The Second Property states A@(B@C) = (A@B)@C

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

Matrix C: 
[[ 5  6  8]
 [12  4  7]
 [ 8  9  8]]

A@(B@C)

[[3398 2324 3052]
 [5244 3733 4810]
 [4408 2881 3830]]

(A@B)@C

[[3398 2324 3052]
 [5244 3733 4810]
 [4408 2881 3830]]

Is the Associative Property True? 

True


In [6]:
# Distributive Property #1 (Third Property)
print("The Third Property states A@(B+C) = A@B + A@C")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()
print("Matrix C: \n{}".format(C))
print()

x = A@(B+C)
print("A@(B+C)\n\n{}".format(x))
print()
y = A@B + A@C
print("A@B + A@C\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is the First Distributive Property True? \n")
print(a)

The Third Property states A@(B+C) = A@B + A@C

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

Matrix C: 
[[ 5  6  8]
 [12  4  7]
 [ 8  9  8]]

A@(B+C)

[[264 246 172]
 [425 368 294]
 [300 339 215]]

A@B + A@C

[[264 246 172]
 [425 368 294]
 [300 339 215]]

Is the First Distributive Property True? 

True


In [7]:
# Distributive Property #2 (Fourth Property)
print("The Fourth Property states (B+C)@A = B@A + C@A")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()
print("Matrix C: \n{}".format(C))
print()

x = (B+C)@A
print("(B+C)@A\n\n{}".format(x))
print()
y = B@A + C@A
print("B@A + C@A\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is the Second Distributive Property True? \n")
print(a)

The Fourth Property states (B+C)@A = B@A + C@A

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

Matrix C: 
[[ 5  6  8]
 [12  4  7]
 [ 8  9  8]]

(B+C)@A

[[142 152 305]
 [164 208 377]
 [251 331 497]]

B@A + C@A

[[142 152 305]
 [164 208 377]
 [251 331 497]]

Is the Second Distributive Property True? 

True


In [8]:
# Identity Property (Fifth Property)
print("The Fifth Property states A@I = A")
print()

I = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
print("I:\n{}".format(I))
print()
print("Matrix A: \n{}".format(A))
print()

x = A@I 
print("A@I \n{}".format(x))
print()
y = A

a = np.array_equiv(x,y)
print("Is the Identity Property Correct?\n")
print(a)

The Fifth Property states A@I = A

I:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

A@I 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Is the Identity Property Correct?

True


In [9]:
# Null Property (Sixth Property)
print("The Sixth Property states A@0 = 0")
print()

Z = np.zeros((3,3))
print("Z:\n{}".format(Z))
print()
print("Matrix A: \n{}".format(A))
print()

x = A@Z 
print("A@Z \n{}".format(x))
print()
y = A

a = np.array_equiv(x,y)
print("Does A@Z possess any values other than an array of zeroes?\n")
print(a)

The Sixth Property states A@0 = 0

Z:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

A@Z 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Does A@Z possess any values other than an array of zeroes?

False
