<a href="https://colab.research.google.com/github/emmataguinod/Linear-Algebra_2ndSem/blob/main/Laboratory_2_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 2: Matrices

### Objectives
At the end of this activity you will be able to
1.   Be familiar with matrices and their relation to linear equations.
2.   Perform basic matrix operations.
3.   Program and translate matrix equations and 
operations using Python.





#Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them. 

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$






:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 2 & 2 & 1 & 7 \\ 5 & -2 & -4 & 6 \\ 2 & -7 & -8 &4\end{bmatrix}
$$


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [13]:
## Since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nshape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [14]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

shape:	(2, 2)
Rank:	2



In [15]:
## Declaring a 2 x 3 matrix
G = np.array([
    [1, 2, 5],
    [3, 1, 4]
])
describe_mat(G)

Matrix:
[[1 2 5]
 [3 1 4]]

shape:	(2, 3)
Rank:	2



##Square Matrices

In [22]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nshape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [23]:
square_mat = np.array([
   [2,4,6],
   [5,7,8],  
   [4,2,9]            
])

non_square_mat = np.array([
   [2,4,6],    
   [5,7,8]                    
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[2 4 6]
 [5 7 8]
 [4 2 9]]

shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 4 6]
 [5 7 8]]

shape:	(2, 3)
Rank:	2
Is Square: False



# According to elements

##Null Matrix

In [25]:
def describe_mat(matrix):
  if matrix.size > 0:
     is_square = True if matrix.shape[0] == matrix.shape[1] else False
     print(f'Matrix:\n{matrix}\n\nshape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [26]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


##Zero Matrix

In [27]:
zero_mat_row = np.zeros((1, 2))
zero_mat_sqr = np.zeros((2, 2))
zero_mat_rct = np.zeros((3, 2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##Ones Matrix

In [28]:
ones_mat_row = np.ones((1, 2))
ones_mat_sqr = np.ones((2, 2))
ones_mat_rct = np.ones((3, 2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##Diagonal Matrix

In [33]:
np.array([
   [4,0,0,0],
   [0,6,0,0],
   [0,0,7,0],
   [0,0,0,2]       
])

array([[4, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 2]])

In [32]:
d= np.diag([4,6,7,2])
d.shape[0] == d.shape[1]
d

array([[4, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 2]])

##Identity Matrix

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

##Upper Triangular Matrix

In [36]:
np.array([
   [3,4,5,6],
   [0,6,7,8],
   [0,0,3,4],
   [0,0,0, 4]      
])

array([[3, 4, 5, 6],
       [0, 6, 7, 8],
       [0, 0, 3, 4],
       [0, 0, 0, 4]])

##Lower Triangular Matrix

In [38]:
np.array([
   [3,0,0,0,],
   [4,4,0,0],
   [5,2,3,0],
   [1,3,7, 4]      
])

array([[3, 0, 0, 0],
       [4, 4, 0, 0],
       [5, 2, 3, 0],
       [1, 3, 7, 4]])

##Practice

1. Given he linear combination below, try to create a corresponding matrix representing it.


$$\theta = 5x + 3y - z$$


2. Given he system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [39]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [40]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

In [41]:
I =np.triu(G)
I

array([[1, 7, 8],
       [0, 2, 2],
       [0, 0, 7]])

##Matrix Algebra

##Addition

In [42]:
A = np.array([
    [2,3],     
    [4,5],
    [7,2]
])
B = np.array([
    [7,3],     
    [4,8],
    [3,3]      
])
A+B

array([[ 9,  6],
       [ 8, 13],
       [10,  5]])

In [ ]:
4+A ##Broadcasting

##Subtraction


##Element-wise Multiplication